config/routes.rb
# == Route Map
#
#      Prefix Verb URI Pattern      Controller#Action
#        root GET  /                messages#new
#    messages POST /m(.:format)     messages#create
# new_message GET  /m/new(.:format) messages#new
#     message GET  /m/:id(.:format) messages#show
#         faq GET  /faq(.:format)   static_pages#faq
#             GET  /:id(.:format)   messages#show
#

Rails.application.routes.draw do
  root to: "messages#new"

  resources :messages, path: :m, only: [:new, :create, :show]

  get '/faq', controller: :static_pages, action: :faq
  get '/:id', controller: :messages, action: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  body       :text
#  stub       :string
#  expires_at :datetime
#  created_at :datetime
#  updated_at :datetime
#  read_at    :datetime
#
# Indexes
#
#  index_messages_on_stub  (stub)
#

class Message < ActiveRecord::Base
  attr_reader :key

  validates :body, presence: true, length: { maximum: 4096 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	def render_404
	  render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end
end

app/controllers/concerns/api_error_handlers.rb
module ApiErrorHandlers
  extend ActiveSupport::Concern
  include ::Rack::Utils

  included do
    rescue_from ActionController::ParameterMissing, with: :parameter_missing_error
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found_error
    rescue_from ActiveRecord::RecordInvalid, with: :record_invalid_error
    rescue_from ActiveRecord::RecordNotSaved, with: :record_not_saved_error
  end

  def parameter_missing_error(e)
    handle_error(e.message, status_code(:not_acceptable))
  end

  def record_not_found_error(e)
    handle_error(e.message, status_code(:not_found))
  end

  def record_invalid_error(e)
    handle_error(e.message, status_code(:unprocessable_entity))
  end

  def record_not_saved_error(e)
    handle_error(e.message, status_code(:unprocessable_entity))
  end

  protected

  def handle_error(message, status)
    render json: { error: message }, status: status
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ::ApiErrorHandlers

  def show
    ms = MessagesService.new(params)
    @data = ms.retrieve
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def new
    @message = Message.new
  end

  def create
    ms = MessagesService.new(params)
    key = ms.store

    render json: { data: key }, status: :ok
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.slim
.uk-container
  p
    | Copyright (c) 2017  
    a(href="https://www.linkedin.com/in/jgregorian")
      |  Johanns Gregorian
    br
    | Source code released under MIT license.

app/views/layouts/_navbar.html.slim
nav.uk-navbar-container(uk-navbar)
  .uk-navbar-left
    a.uk-navbar-item.uk-logo(href="#")
      strong Celox.ME
      | ssage
      
    ul.uk-navbar-nav
      li
        = link_to(root_path) do
          span.uk-icon.uk-margin-small-right(uk-icon="icon: pencil")
          | Create
      li
        = link_to(faq_path) do
          span.uk-icon.uk-margin-small-right(uk-icon="icon: question")
          | FAQ

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Celox.ME

    meta(name="viewport" content="width=device-width, initial-scale=1")

    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')
    = javascript_include_tag('application', 'data-turbolinks-track': 'reload')
    
    = csrf_meta_tags

    javascript:
      $(document).on('turbolinks:load', function() {
        $('#nojs').hide();
        $('#js').show();
      });

  body(class="#{controller_name} #{action_name}")    
    #nojs.uk-container.uk-container-center.uk-margin
      .uk-alert.uk-alert-danger
        span(uk-icon="icon: warning")
        | This site requires JavaScript! Please enable JavaScript, and refresh the page.

    #js      
      == render partial: 'layouts/navbar'
      .uk-section.uk-section-muted(uk-height-viewport="expand: true")
        == yield
      .uk-section.uk-section-secondary
        == render partial: 'layouts/footer'

app/views/messages/_form.html.slim
= form_for(@message, remote: true, authenticity_token: true, html: { id: 'messageForm' }) do |f|
  .uk-card-header
    h3.uk-card-title Message Body
  
  .uk-card-body
    = f.text_area :body, id: 'messageBody', style: 'min-height: 16rem; font-size: 1.2rem', class: 'uk-text-area uk-width-1-1', autofocus: true
  
  .uk-card-footer
    = f.submit 'Store', id: 'messageSubmit', class: 'uk-button uk-button-large uk-button-primary'      

    label#messageBodyCounter.uk-margin-small-left
      | 2000

#spinnerModal(uk-modal="center: true; esc-close: false; bg-close: false")
  .uk-modal-dialog.uk-modal-body
    p Securly storing data, please wait...
    div(uk-spinner)
    

app/views/messages/_result.html.slim
#messageResult(style="display: none")
  .uk-card-header
    h3.uk-card-title 
      | This is your secure retrieval address

  .uk-card-body
    textarea.uk-form.uk-width-1-1#messageURI(style="font-size: 1.2rem; min-height: 16rem"
                                       readonly="true"
                                       onclick="this.setSelectionRange(0, 9999);")

  .uk-card-footer
    button.uk-button.uk-button-default.uk-button-large(type="button" uk-toggle="target: #dataModal") 
      | See encrypted data
    
#dataModal(uk-modal)
  .uk-modal-dialog.uk-modal-body
    h4(style="color: black;")
      | Data transmitted to the server for storage:
    pre#clientJson.syntaxJson

app/views/messages/new.html.slim
- content_for :head_page do
  meta(name="turbolinks-cache-control" content="no-cache")

.uk-flex.uk-flex-center.uk-flex-middle
  .uk-container.uk-width-large.uk-width-xlarge.uk-width-xxlarge
    .uk-card.uk-card-default
      == render(partial: 'form')      
      == render(partial: 'result')

app/views/messages/show.html.slim
- content_for :head_page do
  meta(name="turbolinks-cache-control" content="no-cache")

.uk-flex.uk-flex-center.uk-flex-middle
  .uk-container.uk-width-large.uk-width-xlarge.uk-width-xxlarge
    .uk-card.uk-card-default
      .uk-card-header
        h3.uk-card-title 
            | Your message. 

      .uk-card-body
        textarea.uk-form.uk-width-1-1#messageData(style="font-size: 1.2rem; min-height: 16rem"
                                           readonly="true"
                                           onclick="this.setSelectionRange(0, 9999);")
          = @data
     
      .uk-card-footer
        h5
          | This message has been destroyed, and cannot be retrieved again.

app/views/static_pages/faq.slim
.uk-container.uk-container-center
  .uk-grid(data-uk-grid-margin)
    .uk-width-1-1
      h1.uk-h1
        | Check back soon!